apiVersion: v1
kind: Service
metadata:
  name: canivete-api-service
  namespace: canivete
spec:
  type: LoadBalancer
  selector:
    run: canivete-api
  ports:
    - name: canivete-api-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  loadBalancerIP: 172.19.255.221