apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: canivete-api-http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    {{- include "api-chart.selectorLabels" . | nindent 4 }}
